"""Adds repr to each model -- qc

Revision ID: 324e428ae4ee
Revises: e2c35aa63bb4
Create Date: 2023-05-16 16:47:21.234871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '324e428ae4ee'
down_revision = 'e2c35aa63bb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
